<div class="container">
    <div class="row my-row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
            <div class="form">
                <?php $form = $this->form; ?>
                <?php $form->setAttribute('onSubmit', 'event.preventDefault();storeClient()'); ?>
                <?php $form->setAttribute('id', 'createClient'); ?>
                <?php $form->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formhidden($form->get('csrf')); ?>
                <?php echo $this->formhidden($form->get('client_id')); ?>
                <?php echo $this->formrow($form->get('client_name')); ?>
                <!--alert-->
                <div class="row alert-row">
                    <div class="col-md-12 my-col" id="alert-client"></div>
                </div>
                <!--alert-->
                <?php echo $this->formrow($form->get('submit')); ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
