-- MySQL Script generated by MySQL Workbench
-- Ter 03 Mai 2016 23:53:33 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema enquete_sys_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `enquete_sys_db` ;

-- -----------------------------------------------------
-- Schema enquete_sys_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enquete_sys_db` DEFAULT CHARACTER SET latin1 ;
USE `enquete_sys_db` ;

-- -----------------------------------------------------
-- Table `enquete_sys_db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`role` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(255) NOT NULL,
  `role_created_at` DATETIME NOT NULL,
  `role_updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`user` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(200) NOT NULL,
  `user_password` VARCHAR(250) NOT NULL,
  `user_salt` VARCHAR(100) NOT NULL,
  `user_activation_key` VARCHAR(100) NOT NULL,
  `user_created_at` DATETIME NOT NULL,
  `user_updated_at` DATETIME NOT NULL,
  `user_status` TINYINT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC),
  UNIQUE INDEX `user_activation_key_UNIQUE` (`user_activation_key` ASC),
  INDEX `fk_user_role_idx` (`role` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role`)
    REFERENCES `enquete_sys_db`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`survey` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`survey` (
  `survey_id` INT NOT NULL AUTO_INCREMENT,
  `survey_name` VARCHAR(255) NOT NULL,
  `survey_created_at` DATETIME NOT NULL,
  `survey_updated_at` DATETIME NOT NULL,
  `survey_status` TINYINT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`survey_id`),
  INDEX `fk_survey_user1_idx` (`user` ASC),
  CONSTRAINT `fk_survey_user1`
    FOREIGN KEY (`user`)
    REFERENCES `enquete_sys_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`question_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`question_type` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`question_type` (
  `question_type_id` INT NOT NULL AUTO_INCREMENT,
  `question_type_name` VARCHAR(100) NOT NULL,
  `question_type_created_at` DATETIME NOT NULL,
  `question_type_updated_at` DATETIME NOT NULL,
  `question_type_status` TINYINT NOT NULL,
  PRIMARY KEY (`question_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`question` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question_name` VARCHAR(255) NOT NULL,
  `question_created_at` DATETIME NOT NULL,
  `question_updated_at` DATETIME NOT NULL,
  `question_status` TINYINT NOT NULL,
  `question_type` INT NOT NULL,
  `survey` INT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_question_question_type1_idx` (`question_type` ASC),
  INDEX `fk_question_survey1_idx` (`survey` ASC),
  CONSTRAINT `fk_question_question_type1`
    FOREIGN KEY (`question_type`)
    REFERENCES `enquete_sys_db`.`question_type` (`question_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_survey1`
    FOREIGN KEY (`survey`)
    REFERENCES `enquete_sys_db`.`survey` (`survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`answer` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`answer` (
  `answer_id` INT NOT NULL AUTO_INCREMENT,
  `answer_name` VARCHAR(255) NOT NULL,
  `answer_created_at` DATETIME NOT NULL,
  `answer_updated_at` DATETIME NOT NULL,
  `answer_status` TINYINT NOT NULL,
  `answer_is_correct` TINYINT NULL,
  `answer_is_correct_text` TEXT NULL,
  `question` INT NOT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `fk_answer_question1_idx` (`question` ASC),
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question`)
    REFERENCES `enquete_sys_db`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`client` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(255) NOT NULL,
  `client_created_at` DATETIME NOT NULL,
  `client_updated_at` DATETIME NOT NULL,
  `user` INT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_client_user1_idx` (`user` ASC),
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`user`)
    REFERENCES `enquete_sys_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`survey_client_response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`survey_client_response` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`survey_client_response` (
  `survey_client_response_id` INT NOT NULL AUTO_INCREMENT,
  `client` INT NOT NULL,
  `answer` INT NOT NULL,
  `survey_client_response_created_at` DATETIME NOT NULL,
  `survey_client_response_updated_at` DATETIME NOT NULL,
  `survey_client_response_status` TINYINT NOT NULL,
  PRIMARY KEY (`survey_client_response_id`),
  INDEX `fk_survey_client_response_client1_idx` (`client` ASC),
  INDEX `fk_survey_client_response_answer1_idx` (`answer` ASC),
  CONSTRAINT `fk_survey_client_response_client1`
    FOREIGN KEY (`client`)
    REFERENCES `enquete_sys_db`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_client_response_answer1`
    FOREIGN KEY (`answer`)
    REFERENCES `enquete_sys_db`.`answer` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `enquete_sys_db`.`survey_client_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enquete_sys_db`.`survey_client_result` ;

CREATE TABLE IF NOT EXISTS `enquete_sys_db`.`survey_client_result` (
  `survey_client_result_id` INT NOT NULL AUTO_INCREMENT,
  `survey_client_result_correct` INT NOT NULL,
  `survey_client_result_error` INT NOT NULL,
  `survey_client_result_created_at` DATETIME NOT NULL,
  `survey_client_result_updated_at` DATETIME NOT NULL,
  `survey_client_response` INT NOT NULL,
  PRIMARY KEY (`survey_client_result_id`),
  INDEX `fk_survey_client_result_survey_client_response1_idx` (`survey_client_response` ASC),
  CONSTRAINT `fk_survey_client_result_survey_client_response1`
    FOREIGN KEY (`survey_client_response`)
    REFERENCES `enquete_sys_db`.`survey_client_response` (`survey_client_response_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
